### ISSUE TITLE
Random seed is never reset

### ISSUE THREAD

**Issue by selcuk** [AceLewis/spintax#11]
Once `.spin()` is called with a `seed`, the random generator won't be reset in subsequent calls without a `seed` argument.

To reproduce:

```
>>> import spintax
>>> spintax.spin("{foo|bar}", seed="baz")
'bar'
>>> spintax.spin("{foo|Bar}")
'foo'
>>> spintax.spin("{foo|Bar}")
'foo'
>>> spintax.spin("{foo|Bar}")
'foo'
...
```

Pull Request #10 should fix this.

**Comment by AceLewis** [comment]
Thanks for the fix.
