### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by ramazk** [AceLewis/spintax#4]
>>> print spintax.spin("{H|h}ell{o|O}")
ell
>>> print spintax.spin("{H|h}ell{o|O}")
Hell
>>> print spintax.spin("{H|h}ell{o|O}")
Hell
>>> print spintax.spin("{H|h}ell{o|O}")
ell

**Comment by AceLewis** [comment]
I have fixed this issue in the latest commit 5fe73da561261d8c2f5ccc27438a803fd0e6820a and will soon put the latest code on pypi. The issue was only with characters that were only 1 long so I didn't spot the issue in the tests, thank you for noticing.
