### ISSUE TITLE
Blank spin with leading newline

### ISSUE THREAD

**Issue by grigi** [AceLewis/spintax#5]
```py
>>> import spintax
>>> set([spintax.spin("{a|b|c}") for a in range(1000)])
{'a', 'b', 'c'}
>>> set([spintax.spin("{a|\nb|\nc}") for a in range(1000)])
{'a', '\nc', '\nb'}
```

All good so far, then you have a leading newline:

```py
>>> set([spintax.spin("{a\n|b\n|c}") for a in range(1000)])
{'', 'b\n', 'a\n', 'c'}
```
There is a blank value there?

This is on Python3.5

**Comment by AceLewis** [comment]
When I used literals I did only use raw strings, I only tested the backslashes for a pipe however looking into this I have noticed a different error too.

```py
>>> set([spintax.spin(r"{a\n|b\n|c}") for a in range(1000)])
{'a\\n', 'b\\n', 'c'}
```

**Comment by grigi** [comment]
I get the data as human input, hence it is an actual newline character instead of a newline representation (as one would get in raw strings).
To my understanding: `r'a\n' == 'a\\n'` is valid?

**Comment by AceLewis** [comment]
No you are correct, I am looking into what I should do in this situation the issue arises because `\n` is a new line however and the printable characters `a\|` is actually represented as `a\\|`

```py
>>> example_1 = 'a\|b'
>>> example_1
'a\\|b'
>>> print(example_1 )
a\|b

>>> example_2 = 'a\nb'
>>> example_2
'a\nb'
>>> print(example_2)
a
b
```

I am now looking into doing the selection a different way thanks for bringing this to my attention.

**Comment by AceLewis** [comment]
To update you I think I have a working fix for this however I need to rethink the testing on this module before publishing the fix. I have only tested it against this and a few other cases but nothing else. I don't have loads of time so this may take a few days.

**Comment by AceLewis** [comment]
I fixed this issue in commit https://github.com/AceLewis/spintax/commit/e65c4ba0689f6b6fcd578da0fe48cc873edc95ab

**Comment by grigi** [comment]
Thanks for the quick response 👍
