### ISSUE TITLE
add new operator

### ISSUE THREAD

**Issue by dsa046** [AceLewis/spintax#6]
whether it is possible to make support of the operator or in square brackets
for example:
   [one | two | three]
gives a random combination of all three phrases:
   one three two
   three two one
   two three one
etc

**Comment by AceLewis** [comment]
This module was made to parse Spintax, the square bracket notation you are showing does not exist in Spintax and could be confusing to some users. This notation does not exist in Spintax so it would not make sense to implement it into the Spintax parser.

Also the proposition you make does not seem that useful, if you are making a list you would probably want to have that comma separated with an "and" at the end, I don't see that many use cases for it.
