### ISSUE TITLE
python setup.py failed

### ISSUE THREAD

**Issue by hapesurya** [AceLewis/spintax#8]
I already try 

$ pip install spintax
Collecting spintax
  Using cached https://files.pythonhosted.org/packages/4c/85/1f95b9fdd1c2c1bf07d238685b8680d17663070190b646a081855ca192ff/spintax-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9e8asy/spintax/

also from zipped folder 
 
/spintax-master$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools

I m using Python 2.7.15+

Can you help me?

**Comment by AceLewis** [comment]
Python 2 is probably the issue. I will look in 1 week to see if there is a simple fix (until then I am not near a PC).

Python 2 is old and will be retired in less than 2 months, if you are learning you might want to consider learning Pyhton 3. https://pythonclock.org/
