### ISSUE TITLE
AttributeError: module 'spintax' has no attribute 'spin'

### ISSUE THREAD

**Issue by soleimanian** [AceLewis/spintax#9]
HI,
I run this code:
```
import spintax
# Function to generate the super hero name
def GenerateSuperHeroName():
    SuperHeroName = spintax.spin(r"{The |}{Super|Scarlet|Commander|Hydro|Captain|Fantastic|Colossal|Nighthawk|Wild} {Mountain|Hawk|Flame|Claw|Machine|Watchman}")
    return SuperHeroName

# Only print name if it is run directly
if __name__ == "__main__":
    print(GenerateSuperHeroName())

```
and get this error:

AttributeError: module 'spintax' has no attribute 'spin'

**Comment by AceLewis** [comment]
Have you installed this library via pip? What version of Python are you using?

It is also likely that you have a local file called spintax.py that is being imported instead of the library. I just tested this code and it works fine.

**Comment by soleimanian** [comment]
I installed it via PIP. I use Python 3.8.
After renaming the file, it now works fine.
Thank you.

**Comment by AceLewis** [comment]
For future reference, when you do import it will first look for a local file with that name then look in the list of installed modules. So when you did `import spintax` you were just importing your local file not this module.
